### ISSUE TITLE
Error on launch [0.6.1]

### ISSUE THREAD

**Issue by Shirethrone** [ThibautSF/ParadoxosModManager#36]
Hi,

I'm on Ubuntu 18.04 and cannot launch the ModManager. It always throws:
> Error: Could not find or load main class application.ModManager

with Java 8, or
> Error: Could not find or load main class application.ModManager
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

with java 10

Which is strange, because Mod.Manager.class is at the correct location within the .jar file.
Help would be much appreciated

**Comment by techsy730** [comment]
I can confirm this. It used to work in Java 8, but some recent update broke it.

**Comment by ThibautSF** [comment]
Do you have the jre version ?

**Comment by ThibautSF** [comment]
Tested and working on linux (Ubuntu 16.04) with 8u201 and 8u211

**Comment by NBurley93** [comment]
Running 8u212, getting the same issue with application.ModManager not being found

**Comment by ThibautSF** [comment]
Hi
Looks like to be the same error from this issue : https://github.com/keeps/roda-in/issues/321

Can you try this solution ? :
https://github.com/keeps/roda-in/issues/321#issuecomment-373406671

**Comment by NBurley93** [comment]
Yeah, that did the trick. Forgot to install openjfx (package is java-openjfx for anyone using arch)

**Comment by ThibautSF** [comment]
Ok, i will put that in the documentation (it could be useful)

**Comment by TheDogKSP** [comment]
My 2cents:
for 0.7.1 I have openJDK 13 installed plus javafx, but it still didnt want to start (classdef not found exception).

My (dirty?) workaround:
copy the javafx 13 libs to PMM lib folder and start it with:
java --module-path .\libs; --add-modules=javafx.controls -jar "%_CURRENT_FILE_DIR%\ParadoxosModManager.jar"

Maybe useful for someone in a similar situation.
